global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using GameZone_CrudOperations.Services;
global using GameZone_CrudOperations.Models;
global using GameZone_CrudOperations.ViewModels;
global using GameZone_CrudOperations.Data;
global using GameZone_CrudOperations.Settings;
